/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.1/userguide/scala_plugin.html
 */

plugins {
    // Apply the scala plugin to add support for Scala
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.1")
    implementation("commons-io:commons-io:2.6")

    //ocr pipeline
    implementation("net.sourceforge.tess4j:tess4j:4.5.1") //tesseract
    implementation("com.joestelmach:natty:0.13") //natty
    implementation("com.atlascopco:hunspell-bridj:1.0.4") //hunspell
    implementation("org.apache.opennlp:opennlp-tools:1.9.2") //open-nlp-tools
    //opencv
    implementation("org.bytedeco:javacv-platform:1.5.2") //open-nlp-tools

    //akka
    implementation("com.typesafe.akka:akka-stream_2.13:2.6.3")
    implementation("com.typesafe.akka:akka-http_2.13:10.1.11")
    implementation("com.typesafe.akka:akka-http-spray-json_2.13:10.1.11")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.12")
    testImplementation("org.scalatest:scalatest_2.13:3.1.0")
    testImplementation("org.scalatestplus:junit-4-12_2.13:3.1.0.0")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.13:1.2.0")
}
